POST http://localhost:8080/get/list/departmentManagedByEmployee
content-type: application/json

{
     "Department":{
        
    },
    "Employee":{
        "Key":"4:41b0534a-8bbd-4d1b-80ed-d6c4f9f9f1a2:6"
    }
}

# Verified
