POST http://localhost:8080/create/relation/employeeComesUnderDepartment
content-type: application/json

{
    "Employee":{
        "Name":"New Employee",
        "MailAddress":"@gmail.com",
        "Domain":"TO",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    },
    "Department":{
        "DepartmentName":"ISO"
    }
}

# Verified
