POST http://localhost:8080/get/list/employeeCollaboratedWithEmployee
content-type: application/json

{
    "EmployeeN1":{
        "Key":"4:41b0534a-8bbd-4d1b-80ed-d6c4f9f9f1a2:8"
    },
    "CollaboratedWith":{
        
    },
    "EmployeeN2":{
       
    }
}

# verified