# POST http://localhost:8080/get/list/employeeWorksInTools/EMPLOYEE
POST http://localhost:8080/get/list/employeeWorksInTools/TOOL
content-type: application/json

# {
#     "Employee":{
     
#     },
#     "WorksIn":{
       
#     },
#     "Tool":{
#         "Key":"4:41b0534a-8bbd-4d1b-80ed-d6c4f9f9f1a2:22"
#     }
# }

{
    "Employee":{
     "Key":"4:41b0534a-8bbd-4d1b-80ed-d6c4f9f9f1a2:21"
    },
    "WorksIn":{
       
    },
    "Tool":{
        
    }
}

# Verified