POST http://localhost:8080/create/relation/toolComesUnderDomain
content-type: application/json

{
    "Tool":{
        "Name":"D5O1S",
        "DeliveryFormat":"Open Source",
    },
    "Domain":{
        "DomainName":"Tool3" 
    }
}

# verified