POST http://localhost:8080/create/relation/toolManagedByEmployee
content-type: application/json

{
    "Tool":{
        "Name":"New A",
        "ToolDeliveryFormat":"github",
        "ApprovalType":"Manager"
    },
    "Employee":{
        "Name":"New B",
        "MailAddress":"@gmail.com",
        "Domain":"TO",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    }
}

# verified