POST http://localhost:8080/create/relation/toolAccessToEmployee
content-type: application/json

{
    "Tool":{
        "Name":"A",
		"DeliveryFormat":'Open Source'
    },
    "AccessTo":{
      "AccessType":"Lvl 1"  
    },
    "Employee":{
        "Name":"Manager",
        "MailAddress":"Manager@gmail.com",
        "Domain":"TO",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Manager",
        "Location":"Pune"
    }
}

# verified