POST http://localhost:8080/get/list/toolComesUnderDepartment/TOOL
content-type: application/json

{
    "Tool":{
        "Name":"B",
        "ApprovalType":"Manager"
    },
    "AccessType":"Lvl 1",
    "Department":{
        "DepartmentName":"ISO"
    },
}
