POST http://localhost:8080/create/relation/employeeCollaboratedWithEmployee
content-type: application/json

{
    "EmployeeN1":{
        "Name":"A",
        "MailAddress":"1@gmail.com",
        "Domain":"TO1",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    },
    "CollaboratedWith":{
        "TaskDescription":"A"
    },
    "EmployeeN2":{
        "Name":"B",
        "MailAddress":"1@gmail.com",
        "Domain":"TO1",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    }
}

# verified