POST http://localhost:8080/create/relation/employeeSkilledInSkills
content-type: application/json

{
    "Employee":{
        "Name":"Java",
        "MailAddress":"@gmail.com",
        "Domain":"TO",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    },
    "SkilledIn":{
        "Experience":"2"
    },
    "Skills":{
        "SkillName":"Java"
    }
}

# Verified
