POST http://localhost:8080/create/relation/employeeWorksInTools
content-type: application/json

{
    "Employee":{
        "Name":"B",
        "MailAddress":"@gmail.com",
        "Domain":"TO",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    },
    "WorksIn":{
        "Role":"Developer"
    },
    "Tool":{
        "Name":"B",
        "ApprovalType":"Manager"
    }
}
