# POST http://localhost:8080/get/list/employeeSkilledInSkills/EMPLOYEE
POST http://localhost:8080/get/list/employeeSkilledInSkills/SKILLS
content-type: application/json

# {
#     "Employee":{
#     },
#     "SkilledIn":{
#     },
#     "Skills":{
#        "key":"4:41b0534a-8bbd-4d1b-80ed-d6c4f9f9f1a2:19"
#     }
# }

{
    "Employee":{
        "key":"4:41b0534a-8bbd-4d1b-80ed-d6c4f9f9f1a2:16"
    },
    "SkilledIn":{
    },
    "Skills":{
    }
}

# Verified
