POST http://localhost:8080/create/relation/communiationPostedByEmployee
content-type: application/json

{
    "Communication":{
        "Type":"A",
        "Content":"New post 2"
    },
    "PostedBy":{
        "PostedByDate":"A"
    },
    "Employee":{
        "Name":"A",
        "MailAddress":"1@gmail.com",
        "Domain":"TO1",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    }
}