POST http://localhost:8080/create/relation/communityMemberEmployee
content-type: application/json

{
     "Community":{
        "Name":"B",
        "Description":"C",
        "AccessType":"D"
    },
    "Member":{
        "AddedToCommunityDate":"A"
    },
    "Employee":{
        "Name":"B",
        "MailAddress":"@gmail.com",
        "Domain":"TO",
        "Password":"12345678",
        "PhoneNumber":"12345678",
        "Role":"Developer",
        "Location":"Pune"
    }
}
