POST http://localhost:8080/create/relation/communicationPostedInCommunity
content-type: application/json

{
    "Communication":{
        "Type":"B",
        "Content":"New post 2"
    },
    "PostedIn":{
        "PostedInDate":"A"
    },
    "Community":{
        "Name":"A",
        "Description":"C",
        "AccessType":"D"
    }
}
